[package]
name = "algorithm"
version = "0.1.0"
edition = "2021"
authors = ["£· <liuzh594@qq.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.18"
num-bigint = "0.4.4"
rand = "0.9.0-alpha.1"
